apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name:  account-service
          image: sqshq/piggymetrics-account-service
          env:
            - name: MONGODB_PASSWORD
              value: $MONGODB_PASSWORD
            - name: CONFIG_SERVICE_PASSWORD
              value: $CONFIG_SERVICE_PASSWORD
            - name: ACCOUNT_SERVICE_PASSWORD
              value: $ACCOUNT_SERVICE_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"