apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-mongodb
  template:
    metadata:
      labels:
        app: account-mongodb
    spec:
      containers:
        - name:  account-mongodb
          image: sqshq/piggymetrics-mongodb
          env:
            - name: MONGODB_PASSWORD
              value: $MONGODB_PASSWORD
            - name: INIT_DUMP
              value: account-service-dump.js
           
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"