apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-service
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - name:  statistics-service
          image: sqshq/piggymetrics-statistics-service
          env:
            - name: MONGODB_PASSWORD
              value: $MONGODB_PASSWORD
            - name: STATISTICS_SERVICE_PASSWORD
              value: $STATISTICS_SERVICE_PASSWORD
            - name: CONFIG_SERVICE_PASSWORD
              value: $CONFIG_SERVICE_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"