services:
  todoapi-dev:
    build:
      context: .
      args:
        - USER=${USER:-user} # 利用しているWSL又はLinuxのユーザー名 調べるためのコマンドは whoami
        - USER_ID=${USER_ID:-1000} # 利用しているWSL又はLinuxのユーザーID 調べるためのコマンドは id -u
        - GROUP_ID=${GROUP_ID:-1000} # 利用しているWSL又はLinuxのグループID 調べるためのコマンドは id -g
    image: todoapi-dev
    container_name: todoapi-dev
    ports:
      - "5000:5000"
    environment:
      - urls=http://*:5000
      - Provider=MySQL
      - ConnectionStrings__MySQL=Server=tododb;Database=todoapi;User=todoapi;Password=todoapi;
      - ConnectionStrings__PostgreSQL=Host=tododb;Port=5432;User Id=todoapi;Password=todoapi;Database=todoapi;
      - ConnectionStrings__SQLServer=Server=tododb;Database=todoapi;User Id=sa;Password=Xt0d0ap!;
      - ConnectionStrings__SQLite=Filename=DB/todoapi.db
    volumes:
      - type: bind
        source: ../
        target: /TodoApi
    depends_on:
      - tododb
    tty: true
    command: bash

  tododb:
    image: mariadb
    container_name: tododb
    volumes:
      - type: volume
        source: tododb-data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=todoapi
      - MYSQL_DATABASE=todoapi
      - MYSQL_USER=todoapi
      - MYSQL_PASSWORD=todoapi

  tododb-console:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=tododb
    depends_on:
      - tododb


volumes:
  tododb-data:
    name: tododb-data
