# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}

      # Runs a set of commands using the runners shell
      - name: Deploy Kubernetes
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SERVER }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_KEY }}
          command: |
            cd ${{ secrets.DEPLOY_PATH }}
            git pull
            SKAFFOLD_DEFAULT_REPO=${{ secrets.DOCKER_REGISTRY }} skaffold -n ${{ secrets.DEPLOY_NAMESPACE }} run
