apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
        - name:  auth-mongodb
          image: sqshq/piggymetrics-mongodb
          env:
            - name: MONGODB_PASSWORD
              value: $MONGODB_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"