apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name:  notification-service
          image: sqshq/piggymetrics-notification-service
          env:
            - name: MONGODB_PASSWORD
              value: $MONGODB_PASSWORD
            - name: CONFIG_SERVICE_PASSWORD
              value: $CONFIG_SERVICE_PASSWORD
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: $NOTIFICATION_SERVICE_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"