apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-stream-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbine-stream-service
  template:
    metadata:
      labels:
        app: turbine-stream-service
    spec:
      containers:
        - name:  turbine-stream-service
          image: sqshq/piggymetrics-turbine-stream-service
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: $CONFIG_SERVICE_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"