services:
  todoendpoint:
    build:
      context: ../../TodoEndpoint
    image: todoendpoint
    container_name: todoendpoint
    ports:
      - "5000:80"
    environment:
      - todoui=http://todoui:5000
      - todoui_map=/
      #- todoapi=http://todoapi:5000/api/todoitems
      #- todoapi_map=/api/todoitems
      #- boardapi=http://boardapi:3000/api/boarditems
      #- boardapi_map=/api/boarditems
    depends_on:
      - todoui

  todoui:
    build:
      context: ../../TodoUI
    image: todoui
    container_name: todoui
    #ports: # For Debug
    #  - "5001:5000"
    environment:
      - urls=http://*:5000
      - todoapi=http://todoapi:5000/api/todoitems
      - boardapi=http://boardapi:3000/api/boarditems
    depends_on:
      - todoapi
      - boardapi

  todoapi:
    build:
      context: ../../TodoApi
    image: todoapi
    container_name: todoapi
    #ports: # For Debug
    #  - "5002:5000"
    environment:
      - urls=http://*:5000
      - Provider=MySQL
      - ConnectionStrings__MySQL=Server=tododb;Database=todoapi;User=todoapi;Password=todoapi;
      - ConnectionStrings__PostgreSQL=Host=tododb;Port=5432;User Id=todoapi;Password=todoapi;Database=todoapi;
      - ConnectionStrings__SQLServer=Server=tododb;Database=todoapi;User Id=sa;Password=Xt0d0ap!;
      - ConnectionStrings__SQLite=Filename=DB/todoapi.db
    depends_on:
      - tododb

  tododb:
    image: mariadb
    container_name: tododb
    volumes:
      - type: volume
        source: tododb-data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=todoapi
      - MYSQL_DATABASE=todoapi
      - MYSQL_USER=todoapi
      - MYSQL_PASSWORD=todoapi

  boardapi:
    build:
      context: ../../BoardApi
    image: boardapi
    container_name: boardapi
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=boarddb
      - TYPEORM_USERNAME=boardapi
      - TYPEORM_PASSWORD=boardapi
      - TYPEORM_DATABASE=boardapi
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=dist/**/*.entity.js
      - TYPEORM_MIGRATIONS=dist/migration/**/*.js
    #ports: # For Debug
    #  - "3000:3000"
    depends_on:
      - boarddb

  boarddb:
    image: postgres:alpine
    container_name: boarddb
    environment:
        - POSTGRES_USER=boardapi
        - POSTGRES_PASSWORD=boardapi
        - PGPASSWORD=boardapi
        - POSTGRES_DB=boardapi
    volumes:
        - type: volume
          source: boarddb
          target: /var/lib/postgresql
        - type: volume
          source: boarddb-data
          target: /var/lib/postgresql/data

  tododb-console:
  #boarddb-console:
    image: adminer
    container_name: tododb-console
    #container_name: boarddb-console
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=tododb
      #- ADMINER_DEFAULT_SERVER=boarddb
    depends_on:
      - tododb
      #- boarddb

volumes:
  tododb-data:
    name: tododb-data
  boarddb:
    name: boarddb
  boarddb-data:
    name: boarddb-data